# Generated by Django 4.1.7 on 2023-07-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0002_food_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
