# Generated by Django 4.1.7 on 2023-09-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0003_order_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
