# Generated by Django 4.1.7 on 2023-09-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0005_food_category_food_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
