# Generated by Django 4.1.7 on 2023-09-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0009_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
