# Generated by Django 4.1.7 on 2023-09-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0010_rename_created_at_order_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
