# Generated by Django 4.1.7 on 2023-09-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0011_alter_order_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pub_date',
        ),
    ]
