# Generated by Django 4.1.7 on 2023-10-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0012_remove_order_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_password',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
