# Generated by Django 4.1.7 on 2023-10-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0013_remove_order_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
