# Generated by Django 4.1.7 on 2023-10-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0014_order_customer_phone_number_order_order_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_password',
        ),
    ]
