# Generated by Django 4.1.7 on 2023-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0015_remove_order_order_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
