# Generated by Django 4.1.7 on 2023-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0018_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_password',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
