# Generated by Django 4.1.7 on 2024-12-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0019_rename_order_password_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
