# Generated by Django 4.1.7 on 2024-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodShop', '0021_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
